apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: me-west1-docker.pkg.dev/${PROJECT_ID}/docker-repo/frontend
          ports:
            - containerPort: 8080
          env:
            - name: VITE_BACKEND_URL
              value: "https://backend-240663900746.me-west1.run.app"
