apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/backend:${_TAG}
          ports:
            - containerPort: 8080
