apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: me-west1-docker.pkg.dev/${PROJECT_ID}/docker-repo/backend
          ports:
            - containerPort: 8080
          env:
            - name: GEMINI_API_KEY
              value: "${GEMINI_API_KEY}"
